; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool on Wed Mar 28 2018 11:00:13 GMT-0400 (Eastern Daylight Time)
G91                    ; relative positioning
G1 Z5 F6000 S2         ; lift Z relative to current position
G91 ; relative mode
G1 S1 X-240 Y-240 F3000 ; course home X or Y
G1 S1 X-240 ; course home X
G1 S1 Y-240 ; course home Y
G1 X4 Y4 F600 ; move away from the endstops
G1 S1 X-10 ; fine home X
G1 S1 Y-10 ; fine home Y
G1 S1 Z-300 F6000
