; generated by RepRapFirmware Configuration Tool on Wed Mar 28 2018 11:00:13 GMT-0400 (Eastern Daylight Time)
G91               ; relative positioning
G1 H1 Y-320 F3600 ; move quickly to X axis endstop and stop there (first pass)
G1 H2 Y5 F3600 ; go back a few mm
G1 H1 Y-320 F360  ; move slowly to X axis endstop once more (second pass)