; homeall.g
; called to home all axes
;
; generated by RepRapFirmware Configuration Tool on Wed Mar 28 2018 11:00:13 GMT-0400 (Eastern Daylight Time)
G91                    ; relative positioning
M98 Pdeployprobe.g     ; deploy mechanical Z probe
M98 Phomex.g
M98 Phomey.g
M98 Phomez.g
M98 Pretractprobe.g    ; retract mechanical Z probe