; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Sat Jan 07 2017 20:25:17 GMT-0500 (EST)

; Clear any bed transform
M561

; Probe the bed at 5 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y270 H0 Z-99999
G30 P2 X270 Y270 H0 Z-99999
G30 P3 X270 Y15 H0 Z-99999
G30 P4 X142.5 Y142.5 H0 Z-99999 S

