; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Sat Jan 07 2017 20:25:17 GMT-0500 (EST)

; Lift Z relatively to current position
G91
G1 Z5 F12000

; Back to absolute positioning
G90

; Go to first bed probe point and home the Z axis
G1 X15 Y15 F12000
G30

; Uncomment the following lines to lift Z after probing
;G91
;G1 Z5 F200
;G90
